# Generated by Django 5.0.6 on 2024-07-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
