# Generated by Django 5.0.6 on 2024-07-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_disponibilidade_horario_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
