# Generated by Django 5.0.6 on 2024-07-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_agendamento_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='valor_total',
        ),
    ]
