# Generated by Django 5.0.6 on 2024-08-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cep',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='quantidade_disponivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
