# Generated by Django 5.0.6 on 2024-08-02 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_disponibilidade_quantidade_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='quantidade',
        ),
    ]
