# Generated by Django 5.0.6 on 2024-08-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_equipamento_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cep',
        ),
    ]
