# Generated by Django 5.0.6 on 2024-08-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_agendamento_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
